---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-app-foo
  namespace: argocd
  # finalizers: 
  #   - resource-finalizer.argocd.argoproj.io
spec: 
  project: default
  source: 
    repoURL: https://github.com/adrianamge/argocd-imp.git
    targetRevision: HEAD
    path: environments/staging/first-app
  destination: 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: 
      - validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true

